name: symfony6-discount-calculator
services:
    web:
        container_name: web
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www/html'
            - './docker/my_project.conf:/etc/apache2/sites-enabled/my_project.conf'
            - './docker/php.ini:/usr/local/etc/php/conf.d/custom.ini'
        depends_on:
            - database
    database:
        container_name: mysql
        image: 'mysql:8.0'
        volumes:
            - './mysql:/var/lib/mysql'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: main
        ports:
            - '3306:3306'
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_HOST=database
            - ALLOW_NO_PASSWORD=true
            - PMA_USER=root
    redis: 
        container_name: redis
        image: redis:7.0.0
        ports:
            - '6379:6379'