services:
    database:
        image: 'mysql:8.0'
        volumes:
            - './mysql:/var/lib/mysql'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: main
        ports:
            - '3306:3306'
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_HOST=database
            - ALLOW_NO_PASSWORD=true
            - PMA_USER=root
    redis: 
        image: redis:7.0.0
        ports:
            - '6379:6379'