date.timezone = Europe/Warsaw
output_buffering = On
max_execution_time = 600
max_input_vars = 10000
memory_limit = 2000M
post_max_size = 100M
upload_max_filesize = 100M
session.save_path = /tmp/

[xdebug]
xdebug.mode = debug
xdebug.start_with_request = trigger
# To najważniejsze ustawienie dla Docker Desktop na Windows:
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = VSCODE
; xdebug.log = /var/www/html/storage/logs/xdebug.log
